// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: user_registration_contracts.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RgistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RgistrationRequest) Reset() {
	*x = RgistrationRequest{}
	mi := &file_user_registration_contracts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RgistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RgistrationRequest) ProtoMessage() {}

func (x *RgistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RgistrationRequest.ProtoReflect.Descriptor instead.
func (*RgistrationRequest) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{0}
}

func (x *RgistrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RgistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RgistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserProfileId string                 `protobuf:"bytes,2,opt,name=user_profile_id,json=userProfileId,proto3" json:"user_profile_id,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_user_registration_contracts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetUserProfileId() string {
	if x != nil {
		return x.UserProfileId
	}
	return ""
}

func (x *RegistrationResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type CreateProfileInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileInput) Reset() {
	*x = CreateProfileInput{}
	mi := &file_user_registration_contracts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileInput) ProtoMessage() {}

func (x *CreateProfileInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileInput.ProtoReflect.Descriptor instead.
func (*CreateProfileInput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProfileInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateProfileInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProfileOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProfileId     *string                `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileOutput) Reset() {
	*x = CreateProfileOutput{}
	mi := &file_user_registration_contracts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileOutput) ProtoMessage() {}

func (x *CreateProfileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileOutput.ProtoReflect.Descriptor instead.
func (*CreateProfileOutput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProfileOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateProfileOutput) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

type DeleteProfileInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileInput) Reset() {
	*x = DeleteProfileInput{}
	mi := &file_user_registration_contracts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileInput) ProtoMessage() {}

func (x *DeleteProfileInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileInput.ProtoReflect.Descriptor instead.
func (*DeleteProfileInput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProfileInput) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type DeleteProfileOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileOutput) Reset() {
	*x = DeleteProfileOutput{}
	mi := &file_user_registration_contracts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileOutput) ProtoMessage() {}

func (x *DeleteProfileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileOutput.ProtoReflect.Descriptor instead.
func (*DeleteProfileOutput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProfileOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateUserInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	HashedPassword string                 `protobuf:"bytes,3,opt,name=hashed_password,json=hashedPassword,proto3" json:"hashed_password,omitempty"`
	ProfileId      string                 `protobuf:"bytes,4,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserInput) Reset() {
	*x = CreateUserInput{}
	mi := &file_user_registration_contracts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserInput) ProtoMessage() {}

func (x *CreateUserInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserInput.ProtoReflect.Descriptor instead.
func (*CreateUserInput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserInput) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

func (x *CreateUserInput) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type CreateUserOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserOutput) Reset() {
	*x = CreateUserOutput{}
	mi := &file_user_registration_contracts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserOutput) ProtoMessage() {}

func (x *CreateUserOutput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserOutput.ProtoReflect.Descriptor instead.
func (*CreateUserOutput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{7}
}

func (x *CreateUserOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteUserInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserInput) Reset() {
	*x = DeleteUserInput{}
	mi := &file_user_registration_contracts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserInput) ProtoMessage() {}

func (x *DeleteUserInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserInput.ProtoReflect.Descriptor instead.
func (*DeleteUserInput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserOutput) Reset() {
	*x = DeleteUserOutput{}
	mi := &file_user_registration_contracts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserOutput) ProtoMessage() {}

func (x *DeleteUserOutput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserOutput.ProtoReflect.Descriptor instead.
func (*DeleteUserOutput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_registration_contracts_proto protoreflect.FileDescriptor

const file_user_registration_contracts_proto_rawDesc = "" +
	"\n" +
	"!user_registration_contracts.proto\x12\x1econtracts.v1.user_registration\"Z\n" +
	"\x12RgistrationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x94\x01\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fuser_profile_id\x18\x02 \x01(\tR\ruserProfileId\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\">\n" +
	"\x12CreateProfileInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"b\n" +
	"\x13CreateProfileOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tH\x00R\tprofileId\x88\x01\x01B\r\n" +
	"\v_profile_id\"3\n" +
	"\x12DeleteProfileInput\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"/\n" +
	"\x13DeleteProfileOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x83\x01\n" +
	"\x0fCreateUserInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12'\n" +
	"\x0fhashed_password\x18\x03 \x01(\tR\x0ehashedPassword\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x04 \x01(\tR\tprofileId\",\n" +
	"\x10CreateUserOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0fDeleteUserInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x10DeleteUserOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB?Z\rcontracts/v1/\xaa\x02-UkrPlugin.Service.Users.Temporal.Contracts.V1b\x06proto3"

var (
	file_user_registration_contracts_proto_rawDescOnce sync.Once
	file_user_registration_contracts_proto_rawDescData []byte
)

func file_user_registration_contracts_proto_rawDescGZIP() []byte {
	file_user_registration_contracts_proto_rawDescOnce.Do(func() {
		file_user_registration_contracts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_registration_contracts_proto_rawDesc), len(file_user_registration_contracts_proto_rawDesc)))
	})
	return file_user_registration_contracts_proto_rawDescData
}

var file_user_registration_contracts_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_registration_contracts_proto_goTypes = []any{
	(*RgistrationRequest)(nil),   // 0: contracts.v1.user_registration.RgistrationRequest
	(*RegistrationResponse)(nil), // 1: contracts.v1.user_registration.RegistrationResponse
	(*CreateProfileInput)(nil),   // 2: contracts.v1.user_registration.CreateProfileInput
	(*CreateProfileOutput)(nil),  // 3: contracts.v1.user_registration.CreateProfileOutput
	(*DeleteProfileInput)(nil),   // 4: contracts.v1.user_registration.DeleteProfileInput
	(*DeleteProfileOutput)(nil),  // 5: contracts.v1.user_registration.DeleteProfileOutput
	(*CreateUserInput)(nil),      // 6: contracts.v1.user_registration.CreateUserInput
	(*CreateUserOutput)(nil),     // 7: contracts.v1.user_registration.CreateUserOutput
	(*DeleteUserInput)(nil),      // 8: contracts.v1.user_registration.DeleteUserInput
	(*DeleteUserOutput)(nil),     // 9: contracts.v1.user_registration.DeleteUserOutput
}
var file_user_registration_contracts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_registration_contracts_proto_init() }
func file_user_registration_contracts_proto_init() {
	if File_user_registration_contracts_proto != nil {
		return
	}
	file_user_registration_contracts_proto_msgTypes[1].OneofWrappers = []any{}
	file_user_registration_contracts_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_registration_contracts_proto_rawDesc), len(file_user_registration_contracts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_registration_contracts_proto_goTypes,
		DependencyIndexes: file_user_registration_contracts_proto_depIdxs,
		MessageInfos:      file_user_registration_contracts_proto_msgTypes,
	}.Build()
	File_user_registration_contracts_proto = out.File
	file_user_registration_contracts_proto_goTypes = nil
	file_user_registration_contracts_proto_depIdxs = nil
}
