// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: user_registration_contracts.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED  OperationStatus = 0
	OperationStatus_OPERATION_STATUS_SUCCESS      OperationStatus = 1
	OperationStatus_OPERATION_STATUS_DUPLICATE    OperationStatus = 2
	OperationStatus_OPERATION_STATUS_SYSTEM_ERROR OperationStatus = 3
	OperationStatus_OPERATION_STATUS_ERROR        OperationStatus = 4
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_SUCCESS",
		2: "OPERATION_STATUS_DUPLICATE",
		3: "OPERATION_STATUS_SYSTEM_ERROR",
		4: "OPERATION_STATUS_ERROR",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED":  0,
		"OPERATION_STATUS_SUCCESS":      1,
		"OPERATION_STATUS_DUPLICATE":    2,
		"OPERATION_STATUS_SYSTEM_ERROR": 3,
		"OPERATION_STATUS_ERROR":        4,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_registration_contracts_proto_enumTypes[0].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_user_registration_contracts_proto_enumTypes[0]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{0}
}

// The password is hashed before the workflow is started. Plain text must
// never be written to Temporal history.
type RgistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RgistrationRequest) Reset() {
	*x = RgistrationRequest{}
	mi := &file_user_registration_contracts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RgistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RgistrationRequest) ProtoMessage() {}

func (x *RgistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RgistrationRequest.ProtoReflect.Descriptor instead.
func (*RgistrationRequest) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{0}
}

func (x *RgistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RgistrationRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserProfileId string                 `protobuf:"bytes,2,opt,name=user_profile_id,json=userProfileId,proto3" json:"user_profile_id,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_user_registration_contracts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetUserProfileId() string {
	if x != nil {
		return x.UserProfileId
	}
	return ""
}

func (x *RegistrationResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// profile_id is generated deterministically inside the workflow.
type CreateProfileInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ProfileId     string                 `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileInput) Reset() {
	*x = CreateProfileInput{}
	mi := &file_user_registration_contracts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileInput) ProtoMessage() {}

func (x *CreateProfileInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileInput.ProtoReflect.Descriptor instead.
func (*CreateProfileInput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProfileInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateProfileInput) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type CreateProfileOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=contracts.v1.user_registration.OperationStatus" json:"status,omitempty"`
	SystemError   *int64                 `protobuf:"varint,2,opt,name=system_error,json=systemError,proto3,oneof" json:"system_error,omitempty"`
	ProfileId     *string                `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileOutput) Reset() {
	*x = CreateProfileOutput{}
	mi := &file_user_registration_contracts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileOutput) ProtoMessage() {}

func (x *CreateProfileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileOutput.ProtoReflect.Descriptor instead.
func (*CreateProfileOutput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProfileOutput) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *CreateProfileOutput) GetSystemError() int64 {
	if x != nil && x.SystemError != nil {
		return *x.SystemError
	}
	return 0
}

func (x *CreateProfileOutput) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

func (x *CreateProfileOutput) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type DeleteProfileInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileInput) Reset() {
	*x = DeleteProfileInput{}
	mi := &file_user_registration_contracts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileInput) ProtoMessage() {}

func (x *DeleteProfileInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileInput.ProtoReflect.Descriptor instead.
func (*DeleteProfileInput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProfileInput) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type DeleteProfileOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileOutput) Reset() {
	*x = DeleteProfileOutput{}
	mi := &file_user_registration_contracts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileOutput) ProtoMessage() {}

func (x *DeleteProfileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileOutput.ProtoReflect.Descriptor instead.
func (*DeleteProfileOutput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProfileOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// user_id is generated deterministically inside the workflow.
type CreateUserInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	HashedPassword string                 `protobuf:"bytes,3,opt,name=hashed_password,json=hashedPassword,proto3" json:"hashed_password,omitempty"`
	ProfileId      string                 `protobuf:"bytes,4,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	UserId         string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserInput) Reset() {
	*x = CreateUserInput{}
	mi := &file_user_registration_contracts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserInput) ProtoMessage() {}

func (x *CreateUserInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserInput.ProtoReflect.Descriptor instead.
func (*CreateUserInput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserInput) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

func (x *CreateUserInput) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *CreateUserInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateUserOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=contracts.v1.user_registration.OperationStatus" json:"status,omitempty"`
	SystemError   *int64                 `protobuf:"varint,2,opt,name=system_error,json=systemError,proto3,oneof" json:"system_error,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserOutput) Reset() {
	*x = CreateUserOutput{}
	mi := &file_user_registration_contracts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserOutput) ProtoMessage() {}

func (x *CreateUserOutput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserOutput.ProtoReflect.Descriptor instead.
func (*CreateUserOutput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{7}
}

func (x *CreateUserOutput) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *CreateUserOutput) GetSystemError() int64 {
	if x != nil && x.SystemError != nil {
		return *x.SystemError
	}
	return 0
}

func (x *CreateUserOutput) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type DeleteUserInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserInput) Reset() {
	*x = DeleteUserInput{}
	mi := &file_user_registration_contracts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserInput) ProtoMessage() {}

func (x *DeleteUserInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserInput.ProtoReflect.Descriptor instead.
func (*DeleteUserInput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserOutput) Reset() {
	*x = DeleteUserOutput{}
	mi := &file_user_registration_contracts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserOutput) ProtoMessage() {}

func (x *DeleteUserOutput) ProtoReflect() protoreflect.Message {
	mi := &file_user_registration_contracts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserOutput.ProtoReflect.Descriptor instead.
func (*DeleteUserOutput) Descriptor() ([]byte, []int) {
	return file_user_registration_contracts_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_registration_contracts_proto protoreflect.FileDescriptor

const file_user_registration_contracts_proto_rawDesc = "" +
	"\n" +
	"!user_registration_contracts.proto\x12\x1econtracts.v1.user_registration\"U\n" +
	"\x12RgistrationRequest\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHashJ\x04\b\x01\x10\x02\"\x94\x01\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fuser_profile_id\x18\x02 \x01(\tR\ruserProfileId\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"O\n" +
	"\x12CreateProfileInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\tprofileIdJ\x04\b\x02\x10\x03\"\x86\x02\n" +
	"\x13CreateProfileOutput\x12G\n" +
	"\x06status\x18\x01 \x01(\x0e2/.contracts.v1.user_registration.OperationStatusR\x06status\x12&\n" +
	"\fsystem_error\x18\x02 \x01(\x03H\x00R\vsystemError\x88\x01\x01\x12\"\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tH\x01R\tprofileId\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x02R\ferrorMessage\x88\x01\x01B\x0f\n" +
	"\r_system_errorB\r\n" +
	"\v_profile_idB\x10\n" +
	"\x0e_error_message\"3\n" +
	"\x12DeleteProfileInput\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"/\n" +
	"\x13DeleteProfileOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\x0fCreateUserInput\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12'\n" +
	"\x0fhashed_password\x18\x03 \x01(\tR\x0ehashedPassword\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x04 \x01(\tR\tprofileId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userIdJ\x04\b\x01\x10\x02\"\xd0\x01\n" +
	"\x10CreateUserOutput\x12G\n" +
	"\x06status\x18\x01 \x01(\x0e2/.contracts.v1.user_registration.OperationStatusR\x06status\x12&\n" +
	"\fsystem_error\x18\x02 \x01(\x03H\x00R\vsystemError\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\x0f\n" +
	"\r_system_errorB\x10\n" +
	"\x0e_error_message\"*\n" +
	"\x0fDeleteUserInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x10DeleteUserOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xb0\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_SUCCESS\x10\x01\x12\x1e\n" +
	"\x1aOPERATION_STATUS_DUPLICATE\x10\x02\x12!\n" +
	"\x1dOPERATION_STATUS_SYSTEM_ERROR\x10\x03\x12\x1a\n" +
	"\x16OPERATION_STATUS_ERROR\x10\x04B?Z\rcontracts/v1/\xaa\x02-UkrPlugin.Service.Users.Temporal.Contracts.V1b\x06proto3"

var (
	file_user_registration_contracts_proto_rawDescOnce sync.Once
	file_user_registration_contracts_proto_rawDescData []byte
)

func file_user_registration_contracts_proto_rawDescGZIP() []byte {
	file_user_registration_contracts_proto_rawDescOnce.Do(func() {
		file_user_registration_contracts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_registration_contracts_proto_rawDesc), len(file_user_registration_contracts_proto_rawDesc)))
	})
	return file_user_registration_contracts_proto_rawDescData
}

var file_user_registration_contracts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_registration_contracts_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_registration_contracts_proto_goTypes = []any{
	(OperationStatus)(0),         // 0: contracts.v1.user_registration.OperationStatus
	(*RgistrationRequest)(nil),   // 1: contracts.v1.user_registration.RgistrationRequest
	(*RegistrationResponse)(nil), // 2: contracts.v1.user_registration.RegistrationResponse
	(*CreateProfileInput)(nil),   // 3: contracts.v1.user_registration.CreateProfileInput
	(*CreateProfileOutput)(nil),  // 4: contracts.v1.user_registration.CreateProfileOutput
	(*DeleteProfileInput)(nil),   // 5: contracts.v1.user_registration.DeleteProfileInput
	(*DeleteProfileOutput)(nil),  // 6: contracts.v1.user_registration.DeleteProfileOutput
	(*CreateUserInput)(nil),      // 7: contracts.v1.user_registration.CreateUserInput
	(*CreateUserOutput)(nil),     // 8: contracts.v1.user_registration.CreateUserOutput
	(*DeleteUserInput)(nil),      // 9: contracts.v1.user_registration.DeleteUserInput
	(*DeleteUserOutput)(nil),     // 10: contracts.v1.user_registration.DeleteUserOutput
}
var file_user_registration_contracts_proto_depIdxs = []int32{
	0, // 0: contracts.v1.user_registration.CreateProfileOutput.status:type_name -> contracts.v1.user_registration.OperationStatus
	0, // 1: contracts.v1.user_registration.CreateUserOutput.status:type_name -> contracts.v1.user_registration.OperationStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_registration_contracts_proto_init() }
func file_user_registration_contracts_proto_init() {
	if File_user_registration_contracts_proto != nil {
		return
	}
	file_user_registration_contracts_proto_msgTypes[1].OneofWrappers = []any{}
	file_user_registration_contracts_proto_msgTypes[3].OneofWrappers = []any{}
	file_user_registration_contracts_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_registration_contracts_proto_rawDesc), len(file_user_registration_contracts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_registration_contracts_proto_goTypes,
		DependencyIndexes: file_user_registration_contracts_proto_depIdxs,
		EnumInfos:         file_user_registration_contracts_proto_enumTypes,
		MessageInfos:      file_user_registration_contracts_proto_msgTypes,
	}.Build()
	File_user_registration_contracts_proto = out.File
	file_user_registration_contracts_proto_goTypes = nil
	file_user_registration_contracts_proto_depIdxs = nil
}
